version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_ecomerce
      MYSQL_USER: api_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3344:3306"

